server:
  # 端口
  port: 5002

spring:
  application:
    # 项目名称
    name: config
  cloud:
    config:
      server:
        git:
          # git地址
          uri: https://github.com/2200404400/cloud.git
          # 搜索路径，用斜杠分割，星号代表所有（/**）代表目录下所有的文件
          search-paths: config/file/*
          # 跳过SSL证书验证
          skipSslValidation: true
          # 若git不开放则需要填写账号密码
          #username:
          #password:
      # 分支
      label: master
    loadbalancer:
      cache:
        # 高版本Cloud会自动加载Loadbalancer，若是找不到会在控制台Warp（警报），设为false后关闭此功能
        enabled: false


eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://127.0.0.1:5001/eureka
  instance:
    # 描述信息（可选）
    instance-id: 配置