# 端口
server:
  port: 5003

# SpringBoot版本超过2.4后Knife4j需要添加才能运行
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Knife4j
knife4j:
  # 开启功能
  enableAggregation: true
  # 设置模式
  # Cloud 通过访问微服务Http获取数据
  # Disk  通过访问resources中的json获取数据
  cloud:
    # 开启功能
    enable: true
    # 模块地址
    routes:
      # 名称，可以随便取
      - name: 项目
        # 模块的Http地址
        uri: 127.0.0.1:5011
        # 获取Swagger Json信息的Http后缀路径，可以加个问好设置分组，若分组后被访问的模块没有这个组会报错
        location: /v2/api-docs