server:
  # 端口
  port: 5011

spring:
  application:
    # 项目名称
    name: project
  cloud:
    loadbalancer:
      cache:
        # 高版本Cloud会自动加载Loadbalancer，若是找不到会在控制台Warp（警报），设为false后关闭此功能
        enabled: false
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    # 账号
    username: a
    # 满名
    password: a
  mvc:
    pathmatch:
      # 配置mvc路径
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      # 注册中心地址，必须添加/eureka后缀，否则访问不到注册中心
      defaultZone: http://127.0.0.1:5001/eureka
  instance:
    # 描述信息（可选）
    instance-id: 项目